- ini_file: dest=/etc/mysql/my.cnf section=mysqld option={{ item.option }} value={{ item.value }}
  sudo: yes
  with_items:
    - { option: log_bin, value: /var/log/mysql/mysql-bin.log }
    - { option: bind-address, value: 0.0.0.0 }
    - { option: server-id, value: master }
