- service: name=mysql state=stopped
  sudo: yes
- name: "MySQL: Restore Database from Master (1)"
  shell: "ssh {{ mysql_master.ssh_username}}@{{ mysql_master.host }} sudo \"{{ item }}\""
  with_items:
    - "ansible localhost -m file -a 'dest=/tmp/backup state=directory'"
    - "innobackupex --user=root --password={{ mysql_root_password }} /tmp/backup"
- name: "MySQL: Make Target Directory"
  file: name="/tmp/master_data" state=absent
- name: "MySQL: Make Target Directory"
  file: name="/tmp/master_data" state=directory
- name: "MySQL: Restore Database from Master (2)"
  shell: "ssh {{ mysql_master.ssh_username}}@{{ mysql_master.host }} sudo tar -C /tmp/backup -cz . | tar -zx -C /tmp/master_data"
- file: name=/var/lib/mysql state=absent
  sudo: yes
- file: name=/var/lib/mysql state=directory
  sudo: yes
- name: "Restore master data"
  shell: "cd /tmp/master_data/* ; tar -c . | tar -C /var/lib/mysql -x ; chown -Rc mysql:mysql /var/lib/mysql"
  sudo: yes
- name: "Read Master Binlog"
  shell: cd /tmp/master_data/* ; cat xtrabackup_binlog_info  | sed 's/\t.*//'
  register: master_binlog
- name: "Read Master Position"
  shell: cd /tmp/master_data/* ; cat xtrabackup_binlog_info  | sed 's/\S*\t*//'
  register: master_pos
- name: "Set Master Info"
  debug: msg="CHANGE MASTER TO MASTER_HOST=\'{{ mysql_master.host }}\', MASTER_USER=\'{{ mysql_slave.master_username }}, MASTER_PASSWORD=\'{{ mysql_slave.master_password }}, MASTER_LOG_FILE=\'{{ master_binlog.stdout }}\', MASTER_LOG_POS={{ master_pos.stdout }}; SLAVE START"

