# Package Installation

# - name: "MySQL: Setup MySQL U/P"
#   shell: echo "mysql-server mysql-server/root_password password {{ mysql.root.password }}" | debconf-set-selections ; echo "mysql-server mysql-server/root_password_again password {{ mysql.root.password }}" | debconf-set-selections
#   sudo: yes
# - name: "MySQL: Installation"
#   apt: state=present package={{ item }}
#   with_items:
#     - mysql-server
#     - mysql-client
#     - python-mysqldb
#   sudo: yes

- apt_repository: repo='deb http://repo.percona.com/apt trusty main' state=present
  sudo: yes
- name: "MySQL: Setup MySQL U/P"
  shell: echo "percona-server-server-5.5 percona-server-server/root_password password {{ mysql.root.password }}" | debconf-set-selections ; echo "percona-server-server-5.5 percona-server-server/root_password_again password {{ mysql.root.password }}" | debconf-set-selections
  sudo: yes
- name: "MySQL: Installation"
  apt: state=present package={{ item }}
  with_items:
    - percona-server-server-5.5
    - percona-server-client-5.5
    - python-mysqldb
  sudo: yes

