# Package Installation

- apt_key: keyserver=keys.gnupg.net id=1C4CBDCDCD2EFD2A state=present
  sudo: yes
- apt_repository: repo='deb http://repo.percona.com/apt trusty main' state=present
  sudo: yes
- name: "MySQL: Setup MySQL U/P"
  shell: echo "percona-server-server-5.5 percona-server-server/root_password password {{ mysql_root_password }}" | debconf-set-selections ; echo "percona-server-server-5.5 percona-server-server/root_password_again password {{ mysql_root_password }}" | debconf-set-selections
  sudo: yes
- name: "MySQL: Installation"
  apt: state=present package={{ item }}
  with_items:
    - percona-server-server-5.5
    - percona-server-client-5.5
    - percona-xtrabackup
    - python-mysqldb
  sudo: yes

