- name: install the locales package
  apt: pkg=locales state=present

- name: ensure the locale exists
  command: /usr/sbin/locale-gen en_GB.UTF-8

- name: set the locale
  command: /usr/sbin/update-locale LANG=en_GB.UTF-8 --reset
